// flow-typed signature: 912752d4010031f7cb29948cc7cd82c1
// flow-typed version: <<STUB>>/browserify-markdown_v1.0.0/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'browserify-markdown'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'browserify-markdown' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'browserify-markdown/index' {
  declare module.exports: $Exports<'browserify-markdown'>;
}
declare module 'browserify-markdown/index.js' {
  declare module.exports: $Exports<'browserify-markdown'>;
}
