// flow-typed signature: 75c0441925aaef9977711084d5c84729
// flow-typed version: <<STUB>>/errorify_v^0.3.1/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'errorify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'errorify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'errorify/errorify' {
  declare module.exports: any;
}

// Filename aliases
declare module 'errorify/errorify.js' {
  declare module.exports: $Exports<'errorify/errorify'>;
}
