// flow-typed signature: 2dc804196f71fadd9db46ae36d54cb1b
// flow-typed version: <<STUB>>/middleware-proxy_v^2.0.2/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'middleware-proxy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'middleware-proxy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'middleware-proxy/index' {
  declare module.exports: $Exports<'middleware-proxy'>;
}
declare module 'middleware-proxy/index.js' {
  declare module.exports: $Exports<'middleware-proxy'>;
}
