// flow-typed signature: 31fbed0b99c0d6086060e82d20285ed9
// flow-typed version: <<STUB>>/this-commit_v^1.0.0/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'this-commit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'this-commit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'this-commit/index' {
  declare module.exports: $Exports<'this-commit'>;
}
declare module 'this-commit/index.js' {
  declare module.exports: $Exports<'this-commit'>;
}
